sudo: required
services:
  - docker
  
before_install:
  - docker build -t ankamreddyganeshkumar/docker-react -f Dockerfile.dev .
  
script:
  - docker run ankamreddyganeshkumar/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-254067831582"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRETY_KEY"
