sudo: required
services:
  - docker
  
before_install:
  - docker build -t ankamreddyganeshkumar/docker-react -f Dockerfile.dev .
  
script:
  - docker run ankamreddyganeshkumar/docker-react npm run test -- --coverage
